### ISSUE TITLE
에러 핸들링 관련

### ISSUE THREAD

**Issue by jeangho293** [hanghae99-s8realweek-E3/backend#187]
https://github.com/hanghae99-s8realweek-E3/backend/blob/b53d469cda0aea1e641562026cde1dc4fb84bd8a/services/user.service.js#L26

Boom 쓰시다가 new Error로 던지신 이유가 있나요??

**Comment by jangjiyu** [comment]
실수로 Boom 적용을 못 했습니다 
현재는 수정 완료하여 develop_v2 브랜치에 반영해놨고 Main에도 곧 반영할 예정입니다
