### ISSUE TITLE
createToken return 방식

### ISSUE THREAD

**Issue by jeangho293** [hanghae99-s8realweek-E3/backend#188]
https://github.com/hanghae99-s8realweek-E3/backend/blob/b53d469cda0aea1e641562026cde1dc4fb84bd8a/services/user.service.js#L43-L47

https://github.com/hanghae99-s8realweek-E3/backend/blob/b53d469cda0aea1e641562026cde1dc4fb84bd8a/utils/createToken.js#L12

이런 식으로 return 하신 이유가 있나요?? 처음 봤을 때 token을 어디서 선언했는지 파악하지 못했습니다. 유지보수에 어려움이 있을거라 생각되서 말씀드립니다.

**Comment by jangjiyu** [comment]
의견 감사합니다 createToken 모듈에서 토큰 값만 return하도록 수정하여 서비스 단에서 변수 선언 해주는 걸로 수정했습니다
