### ISSUE TITLE
이메일 인증 시 Internal Server Error (500)이 https://2020aurora.shop/api/accounts/emailAuth/check에서 발생하는 문제

### ISSUE THREAD

**Issue by DrunkenNeoguri** [hanghae99-s8realweek-E3/backend#192]

**Comment by jangjiyu** [comment]
![스크린샷 2022-10-02 오후 4 48 28](https://user-images.githubusercontent.com/102751923/193444002-eda63257-de31-4877-b2c1-e7bdcdbeaa65.png)
문제 : 유효성 검증 시 number라는 걸 인식하지 못하고 6자리라고 생각하여 max를 6으로 둔 점
해결 : max를 1000000으로 두어 최대 6자리의 숫자만 검증 통과하게 해결
